FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY maven-web-app/. .
RUN mvn clean package -DskipTests

# --------- Stage 2: Run using Tomcat -------------
FROM tomcat:10.1-jdk17-temurin
COPY --from=build /app/target/*.war /usr/local/tomcat/webapps/ROOT.war
EXPOSE 8080

