apiVersion: v1
kind: Pod
metadata:
  name: javawebpod
  labels:
    name: java
spec:
  containers:
    - name: javaapp
      image: armcool004/javawebapp 
      ports:
        - containerPort: 8080
      
