FROM maven:3.9.4-eclipse-temurin-17 AS build
WORKDIR /app
COPY Business_Management_Project/. .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]

