apiVersion: v1
kind: Pod
metadata:
  name: testing
  labels:
    app: logger
spec:
  containers:
    - name: container-logger
      image: ashokit/sb-logger-app
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pod-svc
spec:
  type: LoadBalancer
  selector:
    app: logger
  ports:
    - port: 80
      targetPort: 8080
