apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-pod
  template:
    metadata:
      labels:
        app: app-pod
    spec:
      containers:
        - name: container-name
          image: gcr.io/google-samples/hello-app:1.0
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 256m
            requests:
              cpu: 50m

