FROM maven:3.9.11-eclipse-temurin-21 AS build
WORKDIR /app
#COPY  bhim-bank/. /app
COPY  kalu/. /app
RUN mvn clean package

#stage 2
FROM eclipse-temurin:21-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","app.jar"]
