FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app
COPY spring-boot-mysql/. .
RUN mvn clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar /app/app.jar
CMD ["pwd"]
ENTRYPOINT ["java","-jar","app.jar"]



