apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-pod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  capacity:
    storage: 200Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /opt/mysql  
