apiVersion: v1
kind: PersistentVolumeClaim 
metadata:
  name: pvc-pod
spec:
  #  volumeName: pv-pod
  accessModes:
    - ReadWriteOnce
  storageClassName: "" 
  resources:
    requests:
      storage: 200Mi

